### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by bitRomney** [logan169/PyWhale#3] opened 2018-02-21 21:57 UTC
I know this seems very basic, but I keep getting an import error whether in my python 3 or 2 env. When I try to run: 
from PyWhale import PyWhale

I get this:
from pywhale.connection.Api import Api
ImportError: No module named pywhale.connection.Api
ImportError: No module named pywhale.connection.Api

Do you know why this could be? I cloned the repo, copied and pasted my demo api key, and still have problems just running that first command, from PyWhale import PyWhale

**Comment by logan169** [comment] 2018-02-24 19:00
You probably trying to import it from outside the app folder.

Because this is not a bug, I'm closing the ticket.
Next time send a mail or ask the question on stackoverflow

**Closed as completed by logan169** 2018-02-24 19:00 UTC
